### ISSUE TITLE
Locale?

### ISSUE THREAD

**Issue by bpuig** [dmackca/vue-filter-number-format#1]
How do I load a locale?

Thanks

**Comment by bpuig** [comment]
Ok, stupid questions, I made it like it says in numeral js docs.

**Comment by dmackca** [comment]
I'm glad you got it working 👍 
I recently released version 2 of this package, which lets you pass in your own `numeral` parameter, so you can configure it with [locales](http://numeraljs.com/#locales) and [custom formats](http://numeraljs.com/#custom-formats) before creating the filter function :)
